### ISSUE TITLE
Organisation

### ISSUE THREAD

**Issue by victorlevasseur** [ElDawgerino/LO07-Publi#1]
Comment on s'organise ? J'ai l'impression de passer mon temps à faire la même chose que toi...

**Comment by zer0tonin** [comment]
Je peux m'occuper de la partie frontend et toi du backend si tu veux.

**Comment by victorlevasseur** [comment]
On fait comme ça.

**Comment by victorlevasseur** [comment]
Si jamais tu veux tester le backend, tu peux utiliser un client REST (comme https://addons.mozilla.org/fr/firefox/addon/poster/ qui est un module complémentaire pour Firefox).

Il faut juste faire attention à bien mettre "application/json" en type de données pour les requêtes. La fonction intégrée pour uploader des fichiers ne fonctionnera pas avec ce backend vu qu'il faut stocker le fichier en base64.

**Comment by zer0tonin** [comment]
Ok, pour l'instant j'utilisait curl, mais je vais jeter un coup d'oeil à ton plugin.
