### ISSUE TITLE
Comment garder le même fichier lors d'un update d'une publi

### ISSUE THREAD

**Issue by victorlevasseur** [ElDawgerino/LO07-Publi#11]
Déjà implémenté côté backend, mais pas côté frontend (voir la doc de publication::update_publication dans publication.php)...

**Comment by zer0tonin** [comment]
J'ai fix par contre j'ai l'impression que le backend n'efface pas le fichier quand on envoie rien.

**Comment by victorlevasseur** [comment]
Bizarre, je regarde ça demain.

Le dim. 12 juin 2016 à 22:42, ElDawgerino notifications@github.com a
écrit :

**Comment by victorlevasseur** [comment]
Si par "supprimer", tu parles de supprimer physiquement le fichier du serveur, ça ne le fait pas en effet. Par contre, ça devrait supprimer l'association du fichier à la publication.

**Comment by zer0tonin** [comment]
J'ai rien dit, c'est juste que le front-end n'envoyait pas vraiment rien.
