### ISSUE TITLE
Recherches encore manquantes

### ISSUE THREAD

**Issue by victorlevasseur** [ElDawgerino/LO07-Publi#12]
D'après le sujet : 
- [x] Liste des publications présente dans la base dans l'ordre chronologique (ordonnée par catégorie et par année) (**déjà fait, mais va être étendu sur la directive directement !**)
- [x] Liste des publications pour un laboratoire donné et à partir d'une année donnée (donc formulaire avec deux paramètres)
- [x] Liste des publications d'un chercheur donné (ordonnée par catégorie et par année)
- [ ] Liste des collaborations extérieures à l'UTT d'un chercheur donné.
- [x] Liste des co-auteurs d'un chercheur donné ordonnée par nombre de co-publications décroissante.

**Comment by victorlevasseur** [comment]
@ElDawgerino

**Comment by zer0tonin** [comment]
Liste des collaborations extérieures à l'UTT d'un chercheur donné, je suis pas trop trop sûr de ce que c'est en fait. C'est pas juste les publication faites par un auteur hors UTT?

**Comment by victorlevasseur** [comment]
Je ne sais pas.

Sinon, on peut accéder aux publications d'un auteur, mais le problème est
qu'il faut le trouver... Il y aurait moyen de créer une page rapide pour
afficher tous les **auteurs** (pas uniquement les utilisateurs, comme le
fait la page d'admin ??)

Le dim. 12 juin 2016 à 22:14, ElDawgerino notifications@github.com a
écrit :

**Comment by zer0tonin** [comment]
Ca peut se faire. 

La page de recherche actuelle, je la supprime ou pas (vu qu'elle est un peu hors sujet)?

**Comment by victorlevasseur** [comment]
Non, je crois qu'il y a tout de même des choses utiles, mais il faut
ajouter aussi le recherche des publications d'une équipe à partir d'une
certaine année (inutile en réalité mais pas pour le prof).

Le dim. 12 juin 2016 à 22:56, ElDawgerino notifications@github.com a
écrit :

**Comment by victorlevasseur** [comment]
Ouais, en fait, on peut ajouter le tri et le groupby directement sur la ~~page d'accueil~~ **directive**, je m'en occupe (ça remplacera quasi l'ancienne recherche)

EDIT : J'ai mis à jour le descriptif de l'issue pour voir toutes les recherches demandées

**Comment by zer0tonin** [comment]
J'ai rajouté une page avec la liste des auteurs.

**Comment by victorlevasseur** [comment]
Ok, super, une recherche dedans c'est possible ? ^^

Sinon, j'ai ajouté le tri et le groupby directement dans la directive, l'utilisateur peut maintenant ajuster ces deux paramètres à la main. Prochaine étape, sauvegarder ça en local storage.
