### ISSUE TITLE
Upload côté client

### ISSUE THREAD

**Issue by victorlevasseur** [ElDawgerino/LO07-Publi#2]
Je te propose d'utiliser angular-base64-upload.js qui permet d'uploader des fichiers en base64. Cela facilite le traitement côté serveur (j'ai déjà commencé à la faire et cela semble bien marcher avec le base64). J'ai déjà inclu le fichier js dans le projet.

**Comment by zer0tonin** [comment]
Je pense qu'il y a pas mal de méthode plus simple pour uploader depuis angular, mais si c'est pratique côté serveur d'avoir du base64 je veux bien.

**Comment by victorlevasseur** [comment]
C'est super pratique en fait. J'ai juste à decoder et c'est bon.
D'ailleurs, c'est pas compliqué avec Angular, cf la doc du module que j'ai
ajouté : https://github.com/adonespitogo/angular-base64-upload (il suffit de rajouter `base-sixty-four-input` dans la balise `<input>` du fichier)
