### ISSUE TITLE
Erreur dans l'upload d'une publication

### ISSUE THREAD

**Issue by zer0tonin** [ElDawgerino/LO07-Publi#4]
En essayant d'upload j'ai : 
Undefined index: username in C:\wamp64\www\LO07-Publi\src \publication.php on line 38

**Comment by victorlevasseur** [comment]
Bien vu, j'ai supprimé le stockage du login utilisateur dans la variable de session (je stocke l'id maintenant). J'avais pas fait gaffe à cela. De toute façon, je suis en train de travailler sur une autre branche avec la nouvelle structure de la bdd. Ce sera de nouveau fonctionnel quand j'aurais fini.
